FROM ubuntu:18.04
MAINTAINER ${USER}
RUN apt-get update
RUN apt-get -qqy install make
RUN apt-get -qqy install gcc-arm-none-eabi
RUN apt-get -qqy install binutils-arm-none-eabi
RUN apt-get -qqy install openocd
RUN apt-get -qqy install binutils
